### ISSUE TITLE
Discussion: Passing Activities versus Interfaces to Presenters

### ISSUE THREAD

**Issue by curioustechizen** [anupcowkur/MVPSample#1]
This sample is a great app to understand the basics of MVP in a simple way!

I had tried something on similar lines but I often came across the opinion that Presenters should never reference any platform-specific components. I attempted to take this advice and split the `Activity`/`Fragment` code into a View Interface:

``` java
//Probably rename the methods to make them platform-neutral
interface PostsView{
    void initRecyclerViewUI();
    void initRecyclerViewAdapter();
}

public class PostsActivity extends Activity implements PostsView {
   //Implementation here
}

public class PostsPresenter {
    public void init(PostsView postsView){
        postsView.initRecyclerViewUI();
        //Rest of the implementation
    }
}
```

This works and is a clean separation of concerns. The Presenters can be reused on desktop or JEE or whatever. 

But I found it quickly leads to a proliferation of View interfaces. That may satisfy "clean code" definitions but one might argue that it makes the flow difficult to follow, especially for the junior developers on the team (same old dogmatic-pragmatic spectrum).

Any thoughts on this? Opinions/preferences?

**Comment by anupcowkur** [comment]
I've seen it done elsewhere with interfaces too and It does provide benefits such as the ability to be reused on desktop/JEE etc

However, I think if you are only targeting an Android app and are going to treat your activities/fragments as views, then I don't see much value in putting another layer of abstraction between it. Why go for complexity where you don't need it? As you rightly point, it can lead to a lot of pointless interfaces that only really every work with one activity or fragment.

This is just a sample app and I intend to demonstrate the underlying principles as simply as possible without fluff so I chose this approach. On a real production app, I'd probably just go with whatever the team decides suits us better. I don't have very strong opinions on this as such.

**Comment by curioustechizen** [comment]
:+1:
