### ISSUE TITLE
More improvements for Dagger2

### ISSUE THREAD

**Issue by miroslavign** [anupcowkur/MVPSample#8]
Hey Anup, 
no real issue here, I was just wondering if you could
spend some time checking (sort of a code review) my new commit:
https://github.com/miroslavign/MVPSample/commit/17bf6de1fa086b4acf2db4e0d3f88344b043e3b2

related to adding more Dagger2 dependencies. 
After your editing, if it looks ok, maybe create a new branch on 
your original repo for this push ? My guess is, others may benefit 
from this as I did from your mvp talk and original code sample.

**Comment by anupcowkur** [comment]
Hey man. Looks good. Dagger 2 is cool but I'd like to keep this particular project as it is since the code is connected to the presentation and it might cause confusion if the sample code doesn't look the same as in the talk.

**Comment by miroslavign** [comment]
Yeah, agreed. It might be confusing. 
Maybe for some new updated talk, extending mvp concepts to more using Dagger2.
Anyway, tnx for the clear presentation and for sharing this.

**Comment by anupcowkur** [comment]
You're welcome 👍
